name: libretro Core Info Package

on:
  # Trigger the workflow on push, but only for the master branch
#  push:
#    branches:
#      - master
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Assets:
    name: Bundle Core Info Files
    runs-on: ubuntu-latest

    steps:
#    - uses: actions/checkout@v2
#    - run: cd dist/info && 7z a -mx=9 info.7z *
#    - name: Upload core info bundle
#      uses: svenstaro/upload-release-action@v2
#      with:
#        repo_token: ${{ secrets.GITHUB_TOKEN }}
#        file: dist/info/info.7z
#        tag: Latest
#        asset_name: info.7z
#        overwrite: true
     - uses: burnett01/rsync-deployments@4.1
       with:
         switches: -avzr -e 'ssh -p ${{ secrets.PORT }}' --delete
         path: README
         remote_path: ${{ secrets.LINUX_PATH_X86_64 }}
         remote_host: ${{ secrets.HOST }}
         remote_port: ${{ secrets.PORT }}
         remote_user: ${{ secrets.USERNAME }}
         remote_key: ${{ secrets.KEY }}
